name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '3 20 * * 3'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: python task.py
        env:
          RECIPIENT: ${{secrets.RECIPIENT}}
          EMAIL_SENDER: ${{secrets.EMAIL_SENDER}}
          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
      - name: Commit and push if changed
        run: |-
          git config user.name "Actions on behalf of Devon Ankar"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
